Ext.define("Monitor.view.center.ErrorInfo", {

	extend: "Ext.window.Window",
	id:"errorInfo",
	title:"충전기 장애발생",
	style:"",
	width:400,
	height:600,
	items:[{
		xtype:"panel",
		border:false,
		id:"errorTitle",
		title:"동대구복합환승센터<br/>충전기 #01(급속)",
		layout:{
			type:"vbox"
		},
		items:[{
			xtype:"container",
			height:"100"
		},{
			xtype:"label",
			text:"장애정보"
		},{
			xtype:"panel",
			border:false,
			layout:{
				type:"hbox"
			},
			items:[{
				xtype:"textfield",
				labelWidth:80,
				width:170,
				editable:false,
				id:"errorCode",
				fieldLabel:"장애코드"
			},{
				xtype:"container",
				width:10
			},{
				labelWidth:80,
				width:170,
				editable:false,
				xtype:"textfield",
				id:"errorKind",
				fieldLabel:"장애분류"
			}]
		},{
			xtype:"container",
			height:20
		},{
			xtype:"textarea",
			labelWidth:80,
			width:350,
			id:"errorDetail",
			editable:false,
			fieldLabel:"상세정보"
		},{
			xtype:"container",
			height:20
		},{
			xtype:"label",
			text:"원격명령"
		},{
			xtype:"container",
			height:20
		},{
			xtype:"panel",
			border:false,
			layout:{
				type:"hbox"
			},
			items:[{
				xtype:"container",
				width:50
			},{
				xtype:"label",
				text:"충전기 재시작"
			},{
				xtype:"container",
				width:150
			},{
				xtype:"button",
				text:"Reset"
			}]
		},{
			xtype:"container",
			height:20
		},{
			xtype:"label",
			text:"장애조치 지시"
		},{
			xtype:"container",
			height:20
		},{
			xtype:"panel",
			border:false,
			layout:{
				type:"hbox"
			},
			items:[{
				xtype:"container",
				width:30
			},{
				xtype:"button",
				text:"담당자"
			},{
				xtype:"container",
				width:30
			},{
				xtype:"button",
				text:"충전기<br/>제조사"
			},{
				xtype:"container",
				width:30
			},{
				xtype:"button",
				text:"유지보수<br/>업체"
			}]
		}]
	}]
});